name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      with:
        php-version: '7.4'
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run-script test
